[package]
name = "rust_aoc_2020"
version = "0.1.0"
authors = ["Michael King <mking@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
aoc = { path = "../../rust_aoc" }
